[package]
name = "wind-tuic"
version.workspace = true
repository.workspace = true
edition.workspace = true
description.workspace = true
license = "MIT OR Apache-2.0"

[features]
default = ["server", "client"]
server = []
client = []

[dependencies]
tokio-util = { version = "*", features = ["codec"] }
bytes = "*"
uuid = "*"
hex = { package = "const-hex", version = "1" }

# Patterns
num_enum = "0.7"
snafu = "0.8"