[workspace]
resolver = "2"

members = [
    "crates/*"
]

[workspace.package]
version = "0.7.6"
repository = "https://github.com/zephry-works/wind"
edition = "2024"
description = "Placeholder"
license = "MIT OR Apache-2.0"


