[workspace]
resolver = "2"

members = [
    "crates/*"
]

[workspace.package]
version = "0.1.1"
repository = "https://github.com/proxy-rs/wind"
edition = "2024"
description = "Placeholder"
license = "MIT OR Apache-2.0"
